#!/bin/bash

port=$1
core=$2

function usage() {
    echo
    echo "Usage: $0 <port> [corename]"
    echo "Corename defaults to the name of the current directory"
    echo
    echo  Example: $0 8025 biblio
    echo "         $0 9999        # will use current dir name as core name"
    echo
    exit 1
}

if [ "$port" == "-h" ]; then
  usage
fi

if [ -z $port ]; then
  usage
fi


if [ -z $core ]; then
    core=`basename $(pwd)`
fi



if [ -z $core ]; then
  wd=`pwd`;
  core=`basename $wd`
fi

if [ -z $SOLR_ROOT ]; then
    if [ ! -z $SOLR_URL ]; then
		components=(${SOLR_URL//\// });

	SOLR_ROOT="${components[0]}/${components[1]}/${components[2]}"
    else
	SOLR_ROOT="http://localhost:$port/solr"
    fi
fi

echo -e "\n\nTargeting ${SOLR_ROOT}"
echo -e "Unloading core $core"

curl "${SOLR_ROOT}/admin/cores?action=UNLOAD&core=$core&wt=json"
